[package]
name = "acp_coordinator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
acp_integrity = { path = "../../integrity/acp_integrity" }
serde_json = "1.0"
